name: Build AutoSleep Mod

on:
  push:
    branches: [ "**" ] # Запускать на любой ветке
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Скачать все ветки сразу

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    # Эта магия найдет gradlew, даже если он потерялся
    - name: Fix permissions and check files
      run: |
        find . -name "gradlew" -exec chmod +x {} \;
        echo "Searching for build.gradle..."
        find . -name "build.gradle"

    - name: Build with Gradle
      run: |
        # Ищем где лежит gradlew и запускаем его там
        GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
        cd $(dirname $GRADLEW_PATH)
        ./gradlew build --no-daemon

    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: AutoSleep-Final-Jar
        path: "**/build/libs/*.jar"
